== Java 21 Demo

'''

=== JEP 446. Scoped Values (preview)

Thread-local variables have two main purposes.

* First, they are connected to a specific thread and can only be accessed by that thread or any threads created by it.
* Second, they remove the need for synchronization.

These variables are typically used to share information or context between threads that come from the same parent. Without thread-local variables, you would have to pass extra object parameters to functions to carry information about the state, session, or context. However, thread local variables also come with a suite of problems:

* *unconstrained mutability*: thread-local variables are mutable and figuring out which methods modified them and in which order can get tricky.
* *unbounded lifetime*: if a variable is not removed from ThreadLocal, it will live there until the thread ends. This can lead to data leaking into unrelated tasks, especially when using a thread pool.
* *Memory Leaks:* Thread data isn't garbage collected until the thread ends. If multiple threads share a thread-local variable, it can be challenging to know when to safely remove it without affecting other threads.
* *Heavy Memory Usage*: When you create a child thread, it inherits all the thread-local variables from their parent. The child thread has to allocate storage for every thread-local variable previously written in the parent thread, which can lead to a significant memory footprint.

IMPORTANT: The introduction of virtual threads has made these issues more pronounced, especially because virtual threads allow you to create many threads that share the same operating system thread, making their usage more complex.


A *scoped value* allows data to be safely and efficiently shared between methods in a large program without resorting to method arguments. They are bound to their thread, just like the `ThreadLocal` variables.

*Scoped values*, values that may be safely and efficiently shared to methods without using method parameters. They are preferred to thread-local variables, especially when using large numbers of virtual threads.

Scoped values make it possible to pass data securely from a caller to a faraway callee through a sequence of intermediate methods that do not declare a parameter for the data and have no access to the data.

*Goals*

* *Ease of use* — share data both within a thread and with child threads to simplify reasoning about data flow.
* *Comprehensibility* — Make the lifetime of shared data visible from the syntactic structure of code.
* *Robustness* — Ensure that data shared by a caller can be retrieved only by legitimate callees.
* *Performance* — *Shared data is immutable*, thus allow sharing by a large number of threads, and to enable runtime optimizations.